### ISSUE TITLE
Submit to AUR

### ISSUE THREAD

**Issue by ryanleesipes** [thebitstick/Habitica#1]
This should definitely be submitted to the AUR (Arch User Repository).

https://aur.archlinux.org/

**Comment by ryanleesipes** [comment]
https://wiki.archlinux.org/index.php/Arch_User_Repository#Submitting_packages

Putting this here so I remember where to do this, I will try and get on this.

**Comment by thebitstick** [comment]
I'm not sure this program would be "enough" to be submitted to the AUR. I think it's best as a simple Github project.
